name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.sha }}


      - name: Report test coverage to DeepSource in a loop for 11 times
        run: |
          # Install the CLI
          curl https://deepsource.io/cli | sh
          for i in {1..5}
          do

              # Create a random file with value for i as the content
              echo "some random value -> " $i > ./.filerandom

              ./bin/deepsource report --analyzer test-coverage --key python --value-file ./.filerandom
              sleep 2
          done
        env:
          DEEPSOURCE_DSN: https://968dff5b0ad0466d9125a21828f5dbc4@app.deepsource.com
